---
 - hosts: homelab
   remote_user: root
   become: true
   vars: 
     user_name: tom
     hashed_password: '$6$8YVk/M.PR5FT$At6Dx0uPEjEEuRnbNCGPZHlPnC.TBn9nJ2qCfQ603zB/kuyYNVi9H0lxBHJkY0/PkAbXp/B0LsOEJZFuCjxzW/'
   tasks:
   - name: Create a login user
     user: name={{ user_name }}
           password={{ hashed_password }}
           shell=/bin/bash      
           createhome=yes        
           home=/home/tom
   - name: Connect SSH keys
     authorized_key: user={{ user_name }} key="{{ lookup('file', '/home/tunseyi/.ssh/id_rsa.pub') }}"
   - name: Give user sudo privilege
     lineinfile: dest=/etc/sudoers
                 regexp="{{ user_name }} ALL"
                 line="{{ user_name }} ALL=(ALL) ALL"
                 state=present
   - name: Disable Root Login
     lineinfile: dest=/etc/ssh/sshd_config
                 regexp='^PermitRootLogin'
                 line="PermitRootLogin no"
                 state=present
                 backup=yes
     notify:
       - restart ssh
 
   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
